apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - image: asia-southeast2-docker.pkg.dev/sleep-448714/notifications/production
        name: notifications
        env:
          - name: PORT
            value: "3000"
          - name: GOOGLE_OAUTH_CLIENT_ID
            value: 1036523826752-ounuiqvp6dvl7kqg6730oej08700aggs.apps.googleusercontent.com
          - name: SMTP_USER
            value: "sleeprmailer@gmail.com"
          - name: GOOGLE_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google
                key: clientSecret
          - name: GOOGLE_OAUTH_REFRESH_TOKEN
            valueFrom:
              secretKeyRef:
                name: google
                key: refreshToken
        ports:
          - containerPort: 3000
