steps:
  # reservations
  - name: "gcr.io/cloud-builders/docker"
    args: [
      'build',
      '-t',
      'asia-southeast2-docker.pkg.dev/sleep-448714/reservations/production',
      '-f',
      'apps/reservations/Dockerfile',
      '.'
    ]
  - name: "gcr.io/cloud-builders/docker"
    args: [
      'push',
      'asia-southeast2-docker.pkg.dev/sleep-448714/reservations/production'
    ]
  # auth
  - name: "gcr.io/cloud-builders/docker"
    args: [
      'build',
      '-t',
      'asia-southeast2-docker.pkg.dev/sleep-448714/auth/production',
      '-f',
      'apps/auth/Dockerfile',
      '.'
    ]
  - name: "gcr.io/cloud-builders/docker"
    args: [
      'push',
      'asia-southeast2-docker.pkg.dev/sleep-448714/auth/production'
    ]
  # notifications
  - name: "gcr.io/cloud-builders/docker"
    args: [
      'build',
      '-t',
      'asia-southeast2-docker.pkg.dev/sleep-448714/notifications/production',
      '-f',
      'apps/notifications/Dockerfile',
      '.'
    ]
  - name: "gcr.io/cloud-builders/docker"
    args: [
      'push',
      'asia-southeast2-docker.pkg.dev/sleep-448714/notifications/production'
    ]
  # payments
  - name: "gcr.io/cloud-builders/docker"
    args: [
      'build',
      '-t',
      'asia-southeast2-docker.pkg.dev/sleep-448714/payments/production',
      '-f',
      'apps/payments/Dockerfile',
      '.'
    ]
  - name: "gcr.io/cloud-builders/docker"
    args: [
      'push',
      'asia-southeast2-docker.pkg.dev/sleep-448714/payments/production'
    ]
options:
  logging: CLOUD_LOGGING_ONLY   # Logs go to Cloud Logging (Stackdriver)
  # Alternative: Use REGIONAL_USER_OWNED_BUCKET if you want logs in Cloud Storage
  # defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
timeout: 900s  # Optional: Set timeout (15 min)

serviceAccount: 'projects/sleep-448714/serviceAccounts/1036523826752-compute@developer.gserviceaccount.com'  
  