apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservation
  name: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
      - image: asia-southeast2-docker.pkg.dev/sleep-448714/reservations/production
        name: reservations
